import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ClipboardCheck, TrendingDown } from "lucide-react";
import React from "react";

export default function ReportsInsights() {
  const report = trpc.operations.reports.useQuery();
  if (report.isLoading || !report.data) return <div className="grid gap-4 sm:grid-cols-3">{Array.from({ length: 3 }, (_, index) => <div className="h-36 animate-pulse rounded-2xl bg-slate-100" key={index} />)}</div>;
  const data = report.data;
  return <><section className="mb-6"><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-700">Manager accountability</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950 sm:text-3xl">Operational insights</h1><p className="mt-1 max-w-3xl text-sm text-slate-500">Review WhatsApp compliance, department performance, operational risk signals, and recurring issue patterns for manager meetings.</p></section><div className="grid gap-4 sm:grid-cols-3"><Card><CardContent className="p-4"><ClipboardCheck className="h-5 w-5 text-teal-700" /><p className="mt-4 text-3xl font-semibold">{data.complianceSummary.hospitalRate}%</p><p className="text-sm text-slate-500">Hospital reply compliance</p></CardContent></Card><Card><CardContent className="p-4"><AlertTriangle className="h-5 w-5 text-amber-600" /><p className="mt-4 text-3xl font-semibold">{data.whatsappSummary.pendingOrNoReply}</p><p className="text-sm text-slate-500">Pending or no-reply tasks</p></CardContent></Card><Card><CardContent className="p-4"><TrendingDown className="h-5 w-5 text-rose-700" /><p className="mt-4 text-3xl font-semibold">{data.whatsappSummary.pointsLost}</p><p className="text-sm text-slate-500">Points lost this month</p></CardContent></Card></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Department comparison</CardTitle><CardDescription>Completed WhatsApp outcomes compared with each department's assigned work.</CardDescription></CardHeader><CardContent className="space-y-4">{data.departmentPerformance.map(row => <div key={row.name}><div className="flex justify-between text-sm"><span className="font-medium text-slate-800">{row.name}</span><span className="text-slate-500">{row.completionRate}%</span></div><Progress value={row.completionRate} className="mt-2 h-2" /><p className="mt-1 text-xs text-slate-500">{row.overdue} overdue · {row.openIssues} open issues</p></div>)}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Repeated problem trends</CardTitle><CardDescription>Issue categories ranked by recorded frequency.</CardDescription></CardHeader><CardContent className="space-y-3">{data.repeatedProblemTrends.map(row => <div className="flex items-center justify-between rounded-xl bg-slate-50 p-3" key={row.category}><span className="text-sm font-medium text-slate-800">{row.category}</span><span className="rounded-full bg-white px-2 py-1 text-xs font-semibold text-slate-600">{row.count}</span></div>)}{!data.repeatedProblemTrends.length && <p className="text-sm text-slate-500">No issue categories have been recorded.</p>}</CardContent></Card></div></>;
}
